### PR TITLE
WIP [MBP-381] Move GitOpsConfig outside the Pattern's Spec

### PR DESCRIPTION
**Pull request by jordigilh**
This PR extracts the `GitOpsConfig` spec from the `Pattern` Spec into a new CRD and controller. The motivation for this change is to allow deploying multiple patterns in the same environment without impacting each other's gitops subscription. Extracting the configuration makes it now possible.

To ensure that only one subscription is used, the controller watches for a CR that matches a specific name and namespace configuration, any other CR that doesn't match will be ignored.

@mbaldessari @beekhof PTAL

### CODE REVIEW

**Comment by mbaldessari** [comment]
I hope we can merge #44 first, so this becomes a bit smaller to review ;) A high-level question: Once we land this here and make a new operator release, I assume we need to change a few things in common/ in order to support this change, correct? I mean today we push only the channel of the gitops repo when we call 'make install' from a pattern: https://github.com/hybrid-cloud-patterns/common/blob/main/operator-install/templates/pattern.yaml . I assume this would have to change somewhat

**Comment by jordigilh** [comment]
> I hope we can merge #44 first, so this becomes a bit smaller to review ;) A high-level question: Once we land this here and make a new operator release, I assume we need to change a few things in common/ in order to support this change, correct? I mean today we push only the channel of the gitops repo when we call 'make install' from a pattern: https://github.com/hybrid-cloud-patterns/common/blob/main/operator-install/templates/pattern.yaml . I assume this would have to change somewhat

Agreed, I'd prefer to have #44 merged first before this one since they both share some common changes.
And you're right: once this lands the installation guide will need to be updated to include an additional step to create the `GitOpsConfig` CR first before deploying patterns. I can take care of that in a separated PR when I come back from PTO :smile:

**Comment by mbaldessari** [comment]
> > I hope we can merge #44 first, so this becomes a bit smaller to review ;) A high-level question: Once we land this here and make a new operator release, I assume we need to change a few things in common/ in order to support this change, correct? I mean today we push only the channel of the gitops repo when we call 'make install' from a pattern: https://github.com/hybrid-cloud-patterns/common/blob/main/operator-install/templates/pattern.yaml . I assume this would have to change somewhat
> 
> Agreed, I'd prefer to have #44 merged first before this one since they both share some common changes. And you're right: once this lands the installation guide will need to be updated to include an additional step to create the `GitOpsConfig` CR first before deploying patterns. I can take care of that in a separated PR when I come back from PTO smile

Ack (I just merged #44) , let's sketch out how we're going to update things in patterns, because as soon as we merge this and make a new operator release, then *every* pattern suddenly needs a change (even old stable branches). So ideally we come up with a plan for not breaking the old way of deploying things (or, less ideally, we do a mass update everywhere at the same time). Let's chat after your PTO.

**Comment by jordigilh** [comment]
Closing PR as agreed with team. The effort to add support for deployment of multiple patterns in a single cluster requires further evaluation as it impacts other facets of the deployment, like the collision of operators between patterns and how to validate compatibility between patterns.

**Comment by beekhof** [comment]
I think we'd want a ConfigMap anyway

**Comment by jordigilh** [comment]
@beekhof @mbaldessari  I propose this approach:

When no gitops subscription found, the operator will create a gitops subscription with given hardcoded values:
* channel: stable
* installplanApproval: automatic
* `SubscriptionConfig` to include  env variable `ARGOCD_CLUSTER_CONFIG_NAMESPACES`=`*`. Note this is a carryover from the existing code but it is not added by default, and I think from looking at the docs that it should not be there since by default it is [cluster scope](https://giter.vip/argoproj-labs/argocd-operator/issues/665) when deployed in `openshift-gitops` namespace, and this flag is to specify which namespaces is argocd [allowed](https://github.com/argoproj-labs/argocd-operator/issues/665) to manage.

This is the behavior I'd expect if someone manually creates the subscription from the UI without making any changes to the default values provided. The difference to the current implementation is that we no longer offer the opportunity to customize the gitops subscription values in the pattern manifest. If the user has a need for different values, they can deploy their custom gitops subscription before they deploy the pattern operator subscription. 

WDYT?

**Comment by jordigilh** [comment]
@mbaldessari @beekhof can you reopen this PR for me? thanks!

**Pull request closed without merging**
